version: "2"
modules-download-mode: readonly

run:
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - contextcheck
    - gosec
    - testifylint
    - errcheck
    - bodyclose
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (os.File).Close
      - (io.Closer).Close
  misspell:
    locale: US
  gosec:
    exclude:
      - G304
      - G301
      - G306
      - G115
output:
  formats:
    colored-line-number: true
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  sort-results: true