name: Robocop check

on:
  pull_request:
    paths: 
      - e2e-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-robocop
      - name: Run robocop
        run: robocop -e 0302,0202,0201,0505,0508 --report all